### ISSUE TITLE
[Question] Spring force

### ISSUE THREAD

**Issue by Hexality** [nightmode/logitech-g27#10]
Hi, came to ask if this api can interace with spring and damper load, can it?

also as a bonus wanted to ask if it can interface with button mapping, can it remap the buttons?
I really want to get rid of Wingman completely because of core isolation on windows 11.

![image](https://user-images.githubusercontent.com/17398632/219790238-c0bb6322-bd89-44a3-9f9f-e60641cfcd9e.png)
wanted to implement those into a node app, but first I need to know if its possible to do these things with the api

**Comment by nightmode** [comment]
I am not sure if it what you are looking for but if you run `test/test-force.js` you can interactively play with the the amount that the wheel wants to turn by itself and the amount the wheel resists turning. Resists turning as in a smooth or gritty feeling when you are turning the wheel. If those commands are what you are looking for they can be set with `forceConstant` and `forceFriction`.

I suspect you can do much more with the Logitech wheels but you'll have to know what low levels commands to send and then use the `relay` or `relayOS` functions. I unfortunately could not find a list of low level commands but that was many years ago.

Not sure about button mapping. If you are running node to listen to the wheel, you can choose to do whatever you want when a certain button is pressed. I don't think you can tell the Logitech wheel to act like one button is pressed when in reality another button was pressed, without node intercepting those requests as they happen.

**Comment by Hexality** [comment]
> I am not sure if it what you are looking for but if you run `test/test-force.js` you can interactively play with the the amount that the wheel wants to turn by itself and the amount the wheel resists turning. Resists turning as in a smooth or gritty feeling when you are turning the wheel. If those commands are what you are looking for they can be set with `forceConstant` and `forceFriction`.
> 
> I suspect you can do much more with the Logitech wheels but you'll have to know what low levels commands to send and then use the `relay` or `relayOS` functions. I unfortunately could not find a list of low level commands but that was many years ago.
> 
> Not sure about button mapping. If you are running node to listen to the wheel, you can choose to do whatever you want when a certain button is pressed. I don't think you can tell the Logitech wheel to act like one button is pressed when in reality another button was pressed, without node intercepting those requests as they happen.

that's exactly what I wanted to know
thanks.
